name: Deploy to smartAgro.mhrsifat.xyz

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up PHP (latest LTS for Laravel 12)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo_mysql, dom, fileinfo, tokenizer, xml, curl
          coverage: none

      # 3. Install Composer dependencies
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Set up Node.js (latest LTS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 5. Install JS dependencies & build frontend
      - name: Install Node dependencies and build
        run: |
          npm ci
          npm run build

      # 6. Deploy to server via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/mhrsifa1/smartagro.mhrsifat.xyz
            git reset --hard
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link || true

